#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: us
  identity:
    hostname: workstation
    password: "$6$nvB6b2SU0W2KtUCy$plMkdTSAGHSo2L5T1af5AR.gZGxEsRNxCa3afHjhk6sNraiSTq9OhFkpwKLYpo0OuHzoMOju9mSqjUdIFpal60"
    username: fps
    realname: Workstation
  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: no
        addresses: [ 192.168.20.129/24 ]
        gateway4: 192.168.20.1
        nameservers:
          addresses: [ 8.8.8.8, 1.1.1.1 ]
  apt:
    geoip: true
    preserve_sources_list: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    layout:
      name: direct
  packages:
    - wget
    - git
    - net-tools
  user-data:
    disable_root: true
  late-commands:
    - curtin in-target --target=/target -- git clone https://github.com/edcoreweb/tools.git /home/fps/tools
    - printf '[Unit]\nDescription=Provisioning\n[Service]\nType=simple\nUser=root\nExecStart=/bin/bash /home/fps/tools/vm/provisioning.sh\n[Install]\nWantedBy=multi-user.target\n' > /target/etc/systemd/system/provisioning.service
    - curtin in-target --target=/target -- ln -fs /etc/systemd/system/provisioning.service /etc/systemd/system/multi-user.target.wants/provisioning.service
